const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.video,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetEffectEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.StartAnim
	];
};
self.C3_JsPropNameTable = [
	{logo: 0},
	{Btnexit: 0},
	{bgload: 0},
	{bgloader: 0},
	{Audio: 0},
	{Touch: 0},
	{UkuranX: 0},
	{UkuranY: 0},
	{Tween: 0},
	{Btninfo: 0},
	{Btnmusic: 0},
	{Btnpetunjuk: 0},
	{Browser: 0},
	{Pin: 0},
	{Btnback: 0},
	{BtnHome: 0},
	{k: 0},
	{bg: 0},
	{Btnnext: 0},
	{Timer: 0},
	{pembahasan: 0},
	{nilai: 0},
	{abcd: 0},
	{ps: 0},
	{latar: 0},
	{Sine: 0},
	{Welcome: 0},
	{capaian: 0},
	{cp: 0},
	{btncp: 0},
	{bb2: 0},
	{tujuan: 0},
	{tpem: 0},
	{btntp: 0},
	{Wrap: 0},
	{Bullet: 0},
	{cloud: 0},
	{UX: 0},
	{UY: 0},
	{judulP: 0},
	{Rotate: 0},
	{globe: 0},
	{inputnama: 0},
	{inputnoab: 0},
	{ketiknama: 0},
	{ketiknoab: 0},
	{identitas: 0},
	{Sine2: 0},
	{bubble: 0},
	{Btnprevious: 0},
	{pend4: 0},
	{LocalStorage: 0},
	{ScoreBestscore: 0},
	{tag: 0},
	{Btnranking: 0},
	{ld: 0},
	{star: 0},
	{globe2: 0},
	{ScoreBestscore2: 0},
	{bglatihan: 0},
	{mathtime: 0},
	{PPlkpd: 0},
	{Tlkpd: 0},
	{start: 0},
	{BS: 0},
	{judulsoal: 0},
	{bgdrag: 0},
	{popupteks: 0},
	{berhasilorno: 0},
	{BESTSKOR: 0},
	{star2: 0},
	{materi: 0},
	{Btnrepeat: 0},
	{cek: 0},
	{judul: 0},
	{pp1: 0},
	{JTP: 0},
	{BtnStart: 0},
	{ps1: 0},
	{confetti: 0},
	{value: 0},
	{Answer: 0},
	{ceritapecahan: 0},
	{gbrilustrasi: 0},
	{FPB: 0},
	{bgsoal: 0},
	{ddsoal: 0},
	{RightWrong: 0},
	{menyederhanakanpecahan: 0},
	{cara1pp: 0},
	{cara2pen: 0},
	{cara2peng: 0},
	{pp: 0},
	{soal1: 0},
	{goodjob: 0},
	{BackSoundOn: 0},
	{BackSound2: 0},
	{Name: 0},
	{Absen: 0},
	{CanSubmit: 0},
	{AnswerRevealed: 0},
	{CountOfValuesEntered: 0},
	{AnswersCorrect: 0},
	{NumberOfAnswersToBeProvided: 0},
	{MaxNumberOfDigitsToBeEntered: 0},
	{Score: 0},
	{HighScore: 0}
];

self.InstanceType = {
	logo: class extends self.ISpriteInstance {},
	Btnexit: class extends self.ISpriteInstance {},
	bgload: class extends self.ISpriteInstance {},
	bgloader: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Btninfo: class extends self.ISpriteInstance {},
	Btnmusic: class extends self.ISpriteInstance {},
	Btnpetunjuk: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Btnback: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	k: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Btnnext: class extends self.ISpriteInstance {},
	pembahasan: class extends self.ITextInstance {},
	abcd: class extends self.ISpriteInstance {},
	ps: class extends self.ISpriteInstance {},
	latar: class extends self.ISpriteInstance {},
	Welcome: class extends self.ITextInstance {},
	cp: class extends self.ITextInstance {},
	btncp: class extends self.ITextInstance {},
	bb2: class extends self.ISpriteInstance {},
	tpem: class extends self.ITextInstance {},
	btntp: class extends self.ITextInstance {},
	cloud: class extends self.ISpriteInstance {},
	judulP: class extends self.ITextInstance {},
	globe: class extends self.ISpriteInstance {},
	inputnama: class extends self.ITextInputInstance {},
	inputnoab: class extends self.ITextInputInstance {},
	ketiknama: class extends self.ITextInstance {},
	ketiknoab: class extends self.ITextInstance {},
	identitas: class extends self.ITextInstance {},
	bubble: class extends self.ISpriteInstance {},
	Btnprevious: class extends self.ISpriteInstance {},
	pend4: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	ScoreBestscore: class extends self.ITextInstance {},
	Btnranking: class extends self.ISpriteInstance {},
	ld: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	globe2: class extends self.ISpriteInstance {},
	ScoreBestscore2: class extends self.ITextInstance {},
	bglatihan: class extends self.ISpriteInstance {},
	mathtime: class extends self.ISpriteInstance {},
	PPlkpd: class extends self.ITextInstance {},
	Tlkpd: class extends self.ITextInstance {},
	start: class extends self.ISpriteInstance {},
	BS: class extends self.ISpriteInstance {},
	judulsoal: class extends self.ITextInstance {},
	bgdrag: class extends self.ISpriteInstance {},
	popupteks: class extends self.ITextInstance {},
	berhasilorno: class extends self.ITextInstance {},
	BESTSKOR: class extends self.ITextInstance {},
	star2: class extends self.ISpriteInstance {},
	materi: class extends self.ITextInstance {},
	Btnrepeat: class extends self.ISpriteInstance {},
	cek: class extends self.ITextInstance {},
	judul: class extends self.ITextInstance {},
	pp1: class extends self.ISpriteInstance {},
	JTP: class extends self.ITextInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	ps1: class extends self.ISpriteInstance {},
	confetti: class extends self.ISpriteInstance {},
	Answer: class extends self.ITextInputInstance {},
	ceritapecahan: class extends self.IWorldInstance {},
	gbrilustrasi: class extends self.ISpriteInstance {},
	FPB: class extends self.ISpriteInstance {},
	bgsoal: class extends self.ISpriteInstance {},
	ddsoal: class extends self.ISpriteInstance {},
	RightWrong: class extends self.ISpriteInstance {},
	menyederhanakanpecahan: class extends self.IWorldInstance {},
	cara1pp: class extends self.IWorldInstance {},
	cara2pen: class extends self.IWorldInstance {},
	cara2peng: class extends self.IWorldInstance {},
	pp: class extends self.ISpriteInstance {},
	soal1: class extends self.ISpriteInstance {},
	goodjob: class extends self.ISpriteInstance {}
}